_layouts/default.html

Hey! Thanks for your work. i3wm is my favorite, I have been using it for over 6 years.

Outdated copyright freaks me out

---

docs/user-contributed/py3status.html

Hi,
I'd like to update py3status page for the upcoming 3.0 please :)
Thanks

update doc for py3status 3.0

---

_docs/i3status.man
docs/i3status.html
i3status/index.html
i3status/manpage.html

This change was made in the main repo but not for the docs
https://github.com/i3/i3status/commit/73620dc876d7f76b9a6771048c5ad0ade94e5bd7

Remove SLOC comments

---

docs/user-contributed/conky-i3bar.html

https://github.com/brndnmtthws/conky/wiki/Convert-to-new-1.10-syntax

Convert conky config to new 1.10 syntax

---

_layouts/default.html

Change copyright to no range set to 2009
https://github.com/i3/i3.github.io/pull/36
https://github.com/i3/i3.github.io/pull/22

Change copyright to 2009

---

downloads/index.html

Update fedora link

---

_docs/userguide

Clarify which versions will need to use the old directives and when they became deprecated.

Clarify default_border/new_window note

---

docs/user-contributed/py3status.html

Hi
I would like to update the py3status documentation please
Thanks!

update py3status documentation

---

_docs/userguide

Add missing "be" and replace preferable by desirable as this is probably what was meant

Fix missing word + fix wording

---

docs/user-contributed/conky-i3bar.html

This is fixing a minor typo error in docs/user-contributed/conky-i3bar.html

Fix minor typo error

---

_docs/repositories
docs/repositories.html

update debian.sur5r.net keyring

---

_docs/buildbot
docs/index.html

Add a warning about the buildbot document

---

docs/user-contributed/swapping-workspaces.html

I forgot to update the script after some users feedback in my Gist :)
The most important change is the addition of `--no-auto-back-and-forth`
Gist & Discussions @ https://gist.github.com/fbrinker/df9cfbc84511d807f45041737ff3ea02

Update display-swap script

---

_layouts/default.html

This PR adds a viewport meta tag which enables the website to adapt to mobile screen sizes. It is the basis for responsive design. I've also removed some deprecated tags from the head and updated some others.

Viewport tag

---

docs/4.9/index.html
docs/index.html

I have done the edits in docs/4.9 and the /docs folder since I was unsure which one is currently in use on the website. This is my first ever PR, so please excuse if I've done something incorrectly in the process.

Added link to i3status. Removed duplicate link to  Debugging.

---

docs/user-contributed/py3status.html

docs/user-contributed/py3status: update github link

---

css/xhtml11.css

Update CSS to enhance responsiveness in the code blocks of the user guide.

Update CSS to enhance responsiveness

---

_docs/hacking-howto
docs/hacking-howto.html

Includes:
- https://github.com/i3/i3/pull/5463
- https://github.com/i3/i3/pull/5464

hacking-howto: Sync with i3

---

_docs/conf/i3html.conf
_layouts/default.html
docs/buildbot.html
docs/debugging-release-version.html
docs/debugging.html
docs/gsoc2013-ideas.html
docs/hacking-howto.html
docs/i3-config-wizard.html
docs/i3-migrate-config-to-v4.html
docs/i3-msg.html
docs/i3-nagbar.html
docs/i3.html
docs/i3bar-protocol.html
docs/i3status.html
docs/ipc.html
docs/layout-saving.html
docs/multi-monitor.html
docs/repositories.html
docs/testsuite.html
docs/tshirts.html
docs/userguide.html
docs/wsbar.html
i3status/manpage.html

Link to i3 GH discussions

---

downloads/index.html

Fix archlinux package link

---

_docs/hacking-howto
_docs/i3bar-workspace-protocol
_docs/testsuite
_docs/userguide
docs/hacking-howto.html
docs/i3bar-workspace-protocol.html
docs/testsuite.html
docs/userguide.html

Did not include "next" changes.

Sync docs with i3 upstream
