- _docs/repositories
- docs/repositories.html
Listing each supported Ubuntu release explicitely is cumbersome and
error-prone. Use a more timeless explanation.
> Simplify explanation of available Ubuntu packages

- downloads/index.html
Apparently the cvsweb instance has moved to a dedicated subdomain. The old address just redirects to the CVS root.
> Fix OpenBSD download link

- _layouts/default.html
Github pages sends a 301 for resources without a trailing slash, which rewrites HTTPS -> HTTP.
This patch should avoid that problem. I've sent an email to support@github, will keep you updated with the response.
> Add trailing slash to local routes.

- docs/user-contributed/swapping-workspaces.html
The old script for swapping monitors had a issue if the first two outputs were not `active`, not making the swap correctly.
I added a `filter` function on top of the retrieved output in order to retrieve only active outputs and swap only between then.
> Fix swap monitors script

- _config.yml
Fixes:
Deprecation: The 'pygments' configuration option has been renamed to
'highlighter'. Please update your config file accordingly. The allowed
values are 'rouge', 'pygments' or null.
Tested with the same jekyll version github is using (3.1.1)
> Fixing pygments option deprecation

- conduct-faq.html
- conduct-reporting.html
- conduct.html
- docs/index.html
fixes https://github.com/i3/i3/issues/2676
Largely copied from django (with attribution). Changed contact addresses and removed paragraphs relating to django events or their organizational structure.
> document code of conduct

- _docs/repositories
- docs/repositories.html
'apt install' does not accept .deb files. Use 'dpkg -i' instead.
> Fix keyring installation instructions

- _docs/refcard.html
- _docs/userguide
- docs/refcard.html
- docs/userguide.html
This is a small change to make it easier for people to find the default shortcut for "focus parent".
> Focus parent

- _docs/userguide
As visible on the i3wm.org-website, the layout in 6.10 is a bit weird.
The command "xrandr --output […]" is not displayed as a command (i.e.
terminal-style), but as regular text, the text accompanying it before
instead is displayed as a command.
This leads to other weird behaviour:
The following section "move window|container to mark <mark>" starts a
new chapter, which I don't think it should, and its accompanying
description is displayed a commands.
Since I don't know how to build this website, this fix might not even
fix it, and it is most certainly not tested. I apologize for that and
strongly second #39.
> fix layouting bug in section 6.10

- _docs/ipc
I wrote [i3.cr](https://github.com/woodruffw/i3.cr) a few weeks ago as a Crystal interface for i3. It supports all message types and subscriptions.
> ipc: Add link to Crystal library

- _docs/userguide
- docs/userguide.html
[[move_to_outputs]] doesn't work currently:
https://i3wm.org/docs/userguide.html#move_to_outputs
This does:
https://i3wm.org/docs/userguide.html#_moving_containers_workspaces_to_randr_outputs
This combines a 'BlockId Element' with an 'anchor'. Both should work
now.
See:
- https://github.com/i3/i3/issues/3225
- https://github.com/i3/i3/pull/3191
> Fix userguide link

- docs/user-contributed/swapping-workspaces.html
From https://www.reddit.com/r/i3wm/comments/9o218m/found_a_bug_in_swapping_workspaces/e7rtorl/
Using `read -a` means a workspace name with a colon breaks (because colon is used as separator in `jq`). A cleaner way is to use `read` into separate variables, which will write the entire tail in the last variable. Also simplifies the if-statement with a `grep` invocation.
> Fix swapping workspaces script colon issue

- _docs/conf/i3html.conf
- _layouts/default.html
- docs/buildbot.html
- docs/debugging-release-version.html
- docs/debugging.html
- docs/gsoc2013-ideas.html
- docs/hacking-howto.html
- docs/i3-config-wizard.html
- docs/i3-migrate-config-to-v4.html
- docs/i3-msg.html
- docs/i3-nagbar.html
- docs/i3.html
- docs/i3bar-protocol.html
- docs/i3status.html
- docs/ipc.html
- docs/layout-saving.html
- docs/manpage.html
- docs/multi-monitor.html
- docs/repositories.html
- docs/testsuite.html
- docs/tree-migrating.html
- docs/tshirts.html
- docs/userguide.html
- docs/wsbar.html
- i3status/manpage.html
A bit late but better late than never right? I only changed the most recent doc footers, not the old versions. I was not able to make it dynamic as the docs don't seem to be jekyll generated at all. I presume this is so that they can be downloaded/crawled or it's simply because they haven't been converted to jekyll dynamic docs yet. I will continue looking into it though and see if they can be made into jekyll docs for the sake of making them dynamic and reducing the massive amount of code duplication. For now though, 2009-present is good enough. Closes #59
> Change copyright notice to show 2009-present

- i3lock/index.html
Add i3lock install instructions. As discussed in https://github.com/i3/i3lock/pull/223
> add install instructions to i3lock page

- _docs/i3status.man
There's a bit of text format inconsistency at section 5.17.
> Correct text formatting in i3status manpage

- docs/repositories.html
I found the docs were a little outdated, per https://github.com/i3/i3/issues/3781
This PR will correct the issue with sur5r.net's URL
> docs/repositories.html | Update URL for debian.sur5r.net to point to https://

- _docs/ipc
There is node's `marks` field not documented in get_tree output:
```
$ i3-msg -t get_tree| jq '.' | grep '"marks"' -B8 -A2
"nodes": [
{
"id": 94075649667232,
"type": "con",
"orientation": "none",
"scratchpad_state": "none",
"percent": 1,
"urgent": false,
"marks": [
"scratch2"
],
--
"nodes": [
{
"id": 94075648820464,
"type": "con",
"orientation": "none",
"scratchpad_state": "none",
"percent": 1,
"urgent": false,
"marks": [
"scratch1"
],
```
> added missing get_tree node field: "marks"

- css/style.css
It looks the same for most of the text, but fixes the scrunched
headings when they wrap, like in
https://i3wm.org/docs/user-contributed/luastatus-i3bar.html
> minor: Correct setting of line-height for text

- css/style.css
This commit does a couple of things:
- we set the base font-size of the body element to 1em, or 16px.
- we use REMs for any other font-size declaration further down.
- we adjust the body font color for improved contrast.
- we use a set of system fonts so the user has the smoothest possible
transition from his OS to our page.
I tweaked a couple of rules to stay as close to the original design as possible.
> Normalize the website typo

- downloads/index.html
Update downloads page to reflect current branch name
Fixes #89 
Signed-off-by: Rob Gill <rrobgill@protonmail.com>
> Use 'stable' branch name in downloads page

- _docs/repositories
- docs/repositories.html
related to https://github.com/i3/i3/issues/4340
The instructions are a little different than for bintray because balto manages the signing key, it seems.
You can go to https://i3.baltorepo.com/i3/i3-autobuild/packages/i3/ and click “register this repository” to get roughly these instructions.
> repositories: describe new balto repositories, not old bintray

- docs/user-contributed/py3status.html
Hi
Noticed some broken links when working through https://i3wm.org/docs/user-contributed/py3status.html.
Couldn't find the user contributed articles in `_docs` as mentioned in the contributing section. If I should update them somewhere else please let me know.
PS. A big thank you to all the maintainers of this awesome project
Alex
> Fix broken py3status links

- _docs/repositories
- docs/repositories.html
Also, since /etc/lsb-release will no longer be around in the future, so switch to /etc/os-release instead.
> Update debian.sur5r.net keyring and repository instructions

- _docs/gsoc2013-ideas
- _docs/i3status.man
- _docs/ipc
- _docs/userguide
- css/style.css
- css/xhtml11.css
- docs/gsoc2013-ideas.html
- docs/i3status.html
- docs/ipc.html
- docs/tree-migrating.html
- docs/user-contributed/conky-i3bar.html
- docs/user-contributed/luastatus-i3bar.html
- docs/user-contributed/lzap-config.html
- docs/user-contributed/workspace-current-output.html
- docs/userguide.html
- i3bar/manpage.html
There are some typos in the documentation.
Fix them via codespell.
> Fix typos via codespell
